//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.Authentication.Common
{
    using System;
    
    public enum LoginStatusStateEnum
    {
		CheckingLogin = 0,
			
		LoginSuccess = 2,
			
		LoginError = 1,
			
		
    }
}