//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.DealCapture.Common
{
    using System;
    
    
    public class ComponentHelper
    {
        
        public const string COMPONENT_NAME = "DealCapture";
        
        public const int COMPONENT_CODE = 2118747166;
    }
}
