//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.DealCapture.Common
{
    using System;
    
    public enum TransitionEnum
    {
		NewTransaction,
			
		ValidationError,
			
		InitMapping,
			
		Reject,
			
		UpdateAndRetry,
			
		TimeOut,
			
		Error,
			
		Accepted,
			
		GetInstrumentSnapshot,
			
		InstrumentSnapshot,
			
		ReferentialUpdated,
			
		UpdateReferential,
			
		
    }
}
