//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
<<<<<<< HEAD:Examples/xcomponent.orderprocessing/OrderProcessing/Order/Common/Properties/AssemblyInfo.cs
[assembly: AssemblyTitle("XComponent.Order.Common")]
=======
[assembly: AssemblyTitle("XComponent.SwaggerPetstore.Common")]
>>>>>>> ded11e7603a1629b3194f0a94a09a55a31a4ee67:Examples/xcomponent.restapiclient/RestConsumer/SwaggerPetstore/Common/Properties/AssemblyInfo.cs
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("neomantis")]
[assembly: AssemblyProduct("XComponent")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]