//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using XComponent.Common.ApiContext;
using Microsoft.FSharp.Collections;
using Microsoft.FSharp.Core;

namespace XComponent.Order.Common
{
    public interface IInternalAPI
    {
		void Init(Context context, string privateTopic = null);

		void CreateOrder(Context context, string privateTopic = null);

		void PublishOrderCreation(Context context, string privateTopic = null);

		void Execute(Context context, string privateTopic = null);

		void PartiallyExecute(Context context, string privateTopic = null);

		void PublishOrderFilled(Context context, string privateTopic = null);

		void PublishOrderPartiallyFilled(Context context, string privateTopic = null);

		void Init(Context context, XComponent.Common.Event.DefaultEvent transitionEvent, string privateTopic = null);

		void CreateOrder(Context context, XComponent.Order.UserObject.OrderInput transitionEvent, string privateTopic = null);

		void PublishOrderCreation(Context context, XComponent.Order.UserObject.OrderCreation transitionEvent, string privateTopic = null);

		void Execute(Context context, XComponent.Order.UserObject.ExecutionInput transitionEvent, string privateTopic = null);

		void PartiallyExecute(Context context, XComponent.Order.UserObject.ExecutionInput transitionEvent, string privateTopic = null);

		void PublishOrderFilled(Context context, XComponent.Order.UserObject.OrderExecution transitionEvent, string privateTopic = null);

		void PublishOrderPartiallyFilled(Context context, XComponent.Order.UserObject.OrderExecution transitionEvent, string privateTopic = null);

		void SendEvent(XComponent.Order.UserObject.OrderInput evt, string privateTopic = null);

		void SendEvent(XComponent.Order.UserObject.OrderCreation evt, string privateTopic = null);

		void SendEvent(XComponent.Order.UserObject.ExecutionInput evt, string privateTopic = null);

		void SendEvent(XComponent.Order.UserObject.OrderExecution evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.Order.UserObject.OrderInput evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.Order.UserObject.OrderCreation evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.Order.UserObject.ExecutionInput evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.Order.UserObject.OrderExecution evt, string privateTopic = null);

	}
}
