//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace XComponent.Order.Common
{
    public enum OrderStateEnum
    {
		Executed = 0,
		PartiallyExecuted = 1,
		Pending = 2,
    }
}