//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using XComponent.Authentication.Common;

namespace XComponent.Authentication.Common.Senders
{
    public class SenderManager
    {
		private static InitializeDefaultEventOnInitializingAuthenticationSender _initializeDefaultEventOnInitializingAuthenticationSender;
		private static InitializationSuccessInitializationSuccessOnUpAuthenticationSender _initializationSuccessInitializationSuccessOnUpAuthenticationSender;
		private static CheckLoginCheckLoginOnCheckingLoginLoginStatusSender _checkLoginCheckLoginOnCheckingLoginLoginStatusSender;

        public static InitializeDefaultEventOnInitializingAuthenticationSender InitializeDefaultEventOnInitializingAuthenticationSender
        {
            get
            {
                return _initializeDefaultEventOnInitializingAuthenticationSender ??
                       (_initializeDefaultEventOnInitializingAuthenticationSender = new InitializeDefaultEventOnInitializingAuthenticationSender());
            }
        }

        public static InitializationSuccessInitializationSuccessOnUpAuthenticationSender InitializationSuccessInitializationSuccessOnUpAuthenticationSender
        {
            get
            {
                return _initializationSuccessInitializationSuccessOnUpAuthenticationSender ??
                       (_initializationSuccessInitializationSuccessOnUpAuthenticationSender = new InitializationSuccessInitializationSuccessOnUpAuthenticationSender());
            }
        }

        public static CheckLoginCheckLoginOnCheckingLoginLoginStatusSender CheckLoginCheckLoginOnCheckingLoginLoginStatusSender
        {
            get
            {
                return _checkLoginCheckLoginOnCheckingLoginLoginStatusSender ??
                       (_checkLoginCheckLoginOnCheckingLoginLoginStatusSender = new CheckLoginCheckLoginOnCheckingLoginLoginStatusSender());
            }
        }

    }
}
