//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.Order.Common
{
    using System;
    
    public enum PartialExecutionFacadeStateEnum
    {
		PartiallyFilled = 0,
			
		
    }
}