//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.Order.Common
{
    using System;
    
    public enum StdEnum
    {
		OrderProcessor = -730646916,
			
		Order = 823593371,
			
		CreationFacade = -109111630,
			
		ExecutionFacade = 934188424,
			
		PartialExecutionFacade = 928146413,
			
		
    }
}
