//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.SlackProxy.Common
{
    using System;
    
    public enum PublishMessageStateEnum
    {
		Publishing = 2,
			
		Published = 1,
			
		Error = 0,
			
		
    }
}