//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace XComponent.SlackProxy.Common
{
    public enum TransitionEnum
    {
		Error,
		Init,
		SendMessage,
		Success,
    }
}