//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.Trade.Common.Senders
{
    using System;
    using XComponent.Trade.Common;
    
    
    public class SenderManager
    {
		private static ProcessOrderCreationOrderCreationOnUpTradeProcessorSender m_processOrderCreationOrderCreationOnUpTradeProcessorSender;
        
        public static ProcessOrderCreationOrderCreationOnUpTradeProcessorSender ProcessOrderCreationOrderCreationOnUpTradeProcessorSender
        {
            get
            {
                if ((m_processOrderCreationOrderCreationOnUpTradeProcessorSender == null))
                {
                    m_processOrderCreationOrderCreationOnUpTradeProcessorSender = new ProcessOrderCreationOrderCreationOnUpTradeProcessorSender();
                }
                return m_processOrderCreationOrderCreationOnUpTradeProcessorSender;
            }
        }
		private static ExecuteTradeTradeExecutionOnUpTradeProcessorSender m_executeTradeTradeExecutionOnUpTradeProcessorSender;
        
        public static ExecuteTradeTradeExecutionOnUpTradeProcessorSender ExecuteTradeTradeExecutionOnUpTradeProcessorSender
        {
            get
            {
                if ((m_executeTradeTradeExecutionOnUpTradeProcessorSender == null))
                {
                    m_executeTradeTradeExecutionOnUpTradeProcessorSender = new ExecuteTradeTradeExecutionOnUpTradeProcessorSender();
                }
                return m_executeTradeTradeExecutionOnUpTradeProcessorSender;
            }
        }
		private static ProcessOrderExecutionOrderExecutionOnUpTradeProcessorSender m_processOrderExecutionOrderExecutionOnUpTradeProcessorSender;
        
        public static ProcessOrderExecutionOrderExecutionOnUpTradeProcessorSender ProcessOrderExecutionOrderExecutionOnUpTradeProcessorSender
        {
            get
            {
                if ((m_processOrderExecutionOrderExecutionOnUpTradeProcessorSender == null))
                {
                    m_processOrderExecutionOrderExecutionOnUpTradeProcessorSender = new ProcessOrderExecutionOrderExecutionOnUpTradeProcessorSender();
                }
                return m_processOrderExecutionOrderExecutionOnUpTradeProcessorSender;
            }
        }
		private static ExecuteTradeExecutionOnExecutedTradeSender m_executeTradeExecutionOnExecutedTradeSender;
        
        public static ExecuteTradeExecutionOnExecutedTradeSender ExecuteTradeExecutionOnExecutedTradeSender
        {
            get
            {
                if ((m_executeTradeExecutionOnExecutedTradeSender == null))
                {
                    m_executeTradeExecutionOnExecutedTradeSender = new ExecuteTradeExecutionOnExecutedTradeSender();
                }
                return m_executeTradeExecutionOnExecutedTradeSender;
            }
        }
		private static CreateTradeTradeOnWaitingForExecutionTradeSender m_createTradeTradeOnWaitingForExecutionTradeSender;
        
        public static CreateTradeTradeOnWaitingForExecutionTradeSender CreateTradeTradeOnWaitingForExecutionTradeSender
        {
            get
            {
                if ((m_createTradeTradeOnWaitingForExecutionTradeSender == null))
                {
                    m_createTradeTradeOnWaitingForExecutionTradeSender = new CreateTradeTradeOnWaitingForExecutionTradeSender();
                }
                return m_createTradeTradeOnWaitingForExecutionTradeSender;
            }
        }
		
    }
}
