//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using XComponent.Common.ApiContext;
using Microsoft.FSharp.Collections;
using Microsoft.FSharp.Core;

namespace XComponent.SwaggerPetstore.Common
{
    public interface IInternalAPI
    {
		void Init(Context context, string privateTopic = null);

		void AddPet(Context context, string privateTopic = null);

		void CreateAddPetHttpRequest(Context context, string privateTopic = null);

		void GetPetById(Context context, string privateTopic = null);

		void CreateGetPetByIdHttpRequest(Context context, string privateTopic = null);

		void SendRequest_AddPetOperation(Context context, string privateTopic = null);

		void SendRequest_GetPetByIdOperation(Context context, string privateTopic = null);

		void ReceiveSuccess_AddPetOperation(Context context, string privateTopic = null);

		void ReceiveSuccess_GetPetByIdOperation(Context context, string privateTopic = null);

		void ReceiveError_AddPetOperation(Context context, string privateTopic = null);

		void ReceiveError_GetPetByIdOperation(Context context, string privateTopic = null);

		void Init(Context context, XComponent.Common.Event.DefaultEvent transitionEvent, string privateTopic = null);

		void AddPet(Context context, XComponent.SwaggerPetstore.UserObject.AddPet transitionEvent, string privateTopic = null);

		void CreateAddPetHttpRequest(Context context, XComponent.SwaggerPetstore.UserObject.AddPetOperation transitionEvent, string privateTopic = null);

		void GetPetById(Context context, XComponent.SwaggerPetstore.UserObject.GetPetById transitionEvent, string privateTopic = null);

		void CreateGetPetByIdHttpRequest(Context context, XComponent.SwaggerPetstore.UserObject.GetPetByIdOperation transitionEvent, string privateTopic = null);

		void SendRequest_AddPetOperation(Context context, XComponent.Common.Event.DefaultEvent transitionEvent, string privateTopic = null);

		void SendRequest_GetPetByIdOperation(Context context, XComponent.Common.Event.DefaultEvent transitionEvent, string privateTopic = null);

		void ReceiveSuccess_AddPetOperation(Context context, XComponent.SwaggerPetstore.UserObject.SuccessResponse transitionEvent, string privateTopic = null);

		void ReceiveSuccess_GetPetByIdOperation(Context context, XComponent.SwaggerPetstore.UserObject.SuccessResponse transitionEvent, string privateTopic = null);

		void ReceiveError_AddPetOperation(Context context, XComponent.SwaggerPetstore.UserObject.ErrorResponse transitionEvent, string privateTopic = null);

		void ReceiveError_GetPetByIdOperation(Context context, XComponent.SwaggerPetstore.UserObject.ErrorResponse transitionEvent, string privateTopic = null);

		void SendEvent(XComponent.SwaggerPetstore.UserObject.AddPet evt, string privateTopic = null);

		void SendEvent(XComponent.SwaggerPetstore.UserObject.AddPetOperation evt, string privateTopic = null);

		void SendEvent(XComponent.SwaggerPetstore.UserObject.GetPetById evt, string privateTopic = null);

		void SendEvent(XComponent.SwaggerPetstore.UserObject.GetPetByIdOperation evt, string privateTopic = null);

		void SendEvent(XComponent.Common.Event.DefaultEvent evt, string privateTopic = null);

		void SendEvent(XComponent.SwaggerPetstore.UserObject.SuccessResponse evt, string privateTopic = null);

		void SendEvent(XComponent.SwaggerPetstore.UserObject.ErrorResponse evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.AddPet evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.AddPetOperation evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.GetPetById evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.GetPetByIdOperation evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.Common.Event.DefaultEvent evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.SuccessResponse evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.ErrorResponse evt, string privateTopic = null);

	}
}
