//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.SwaggerPetstore.Common
{
    using System;
    
    public enum StdEnum
    {
		SwaggerPetstore = -1217457941,
			
		AddPetOperation = -1573098133,
			
		GetPetByIdOperation = 1341262500,
			
		
    }
}
