//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.SwaggerPetstore.Common
{
    using System;
    
    public enum AddPetOperationStateEnum
    {
		SendingRequest = 2,
			
		RequestSent = 1,
			
		SuccessResponseReceived = 3,
			
		ErrorResponseReceived = 0,
			
		
    }
}