//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


<<<<<<< HEAD:Examples/xcomponent.orderprocessing/OrderProcessing/Trade/Common/StdEnum.cs
namespace XComponent.Trade.Common
=======
namespace XComponent.SwaggerPetstore.Common
>>>>>>> ded11e7603a1629b3194f0a94a09a55a31a4ee67:Examples/xcomponent.restapiclient/RestConsumer/SwaggerPetstore/Common/StdEnum.cs
{
    using System;
    
    public enum StdEnum
    {
<<<<<<< HEAD:Examples/xcomponent.orderprocessing/OrderProcessing/Trade/Common/StdEnum.cs
		TradeProcessor = 190855629,
			
		Trade = -729436854,
			
		OrderPartialFillProxy = -103749636,
=======
		SwaggerPetstore = -1217457941,
			
		AddPetOperation = -1573098133,
			
		GetPetByIdOperation = 1341262500,
>>>>>>> ded11e7603a1629b3194f0a94a09a55a31a4ee67:Examples/xcomponent.restapiclient/RestConsumer/SwaggerPetstore/Common/StdEnum.cs
			
		
    }
}
