//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.SwaggerPetstore.Common
{
    using System;
    
    public enum TransitionEnum
    {
		Init,
			
		AddPet,
			
		CreateAddPetHttpRequest,
			
		GetPetById,
			
		CreateGetPetByIdHttpRequest,
			
		SendRequest,
			
		ReceiveSuccess,
			
		ReceiveError,
			
		
    }
}
