//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace XComponent.Trade.Common
{
    public class ComponentHelper
    {
        public const string COMPONENT_NAME = "Trade";
        
        public const int COMPONENT_CODE = -729436854;
    }
}