//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using XComponent.Common.ApiContext;
using Microsoft.FSharp.Collections;
using Microsoft.FSharp.Core;

namespace XComponent.Trade.Common
{
    public interface IInternalAPI
    {
		void Init(Context context, string privateTopic = null);

		void ProcessOrderCreation(Context context, string privateTopic = null);

		void CreateTrade(Context context, string privateTopic = null);

		void ExecuteTrade(Context context, string privateTopic = null);

		void ProcessOrderExecution(Context context, string privateTopic = null);

		void Execute(Context context, string privateTopic = null);

		void Init(Context context, XComponent.Common.Event.DefaultEvent transitionEvent, string privateTopic = null);

		void ProcessOrderCreation(Context context, XComponent.Order.UserObject.OrderCreation transitionEvent, string privateTopic = null);

		void CreateTrade(Context context, XComponent.Trade.UserObject.Trade transitionEvent, string privateTopic = null);

		void ExecuteTrade(Context context, XComponent.Trade.UserObject.TradeExecution transitionEvent, string privateTopic = null);

		void ProcessOrderExecution(Context context, XComponent.Order.UserObject.OrderExecution transitionEvent, string privateTopic = null);

		void Execute(Context context, XComponent.Trade.UserObject.TradeExecution transitionEvent, string privateTopic = null);

		void SendEvent(XComponent.Order.UserObject.OrderCreation evt, string privateTopic = null);

		void SendEvent(XComponent.Trade.UserObject.Trade evt, string privateTopic = null);

		void SendEvent(XComponent.Trade.UserObject.TradeExecution evt, string privateTopic = null);

		void SendEvent(XComponent.Order.UserObject.OrderExecution evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.Order.UserObject.OrderCreation evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.Trade.UserObject.Trade evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.Trade.UserObject.TradeExecution evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.Order.UserObject.OrderExecution evt, string privateTopic = null);

	}
}
