//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace XComponent.TradeCapture.Common
{
    public enum TransactionStateEnum
    {
		ErrorOnMapping = 0,
		Mapping = 1,
		TransactionAccepted = 2,
		TransactionRejected = 3,
		Validation = 4,
		ValidationError = 5,
    }
}