//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.TradeCapture.Common
{
    using System;
    
    public enum XCTradeProcessorStateEnum
    {
		EntryPoint = 0,
			
		
    }
}