using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("XComponent.TradeCapture.UserObject")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("invivoo-grp")]
[assembly: AssemblyProduct("XComponent")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
