//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.SwaggerPetstore.Common.Senders
{
    using System;
    using XComponent.SwaggerPetstore.Common;
    
    
    public class AbstractSender
    {
        
        internal static IInternalAPI internalAPI;
        
        public static void Init(IInternalAPI pInternalAPI)
        {
            internalAPI = pInternalAPI;
        }
    }
}