//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.SwaggerPetstore.Common.Senders
{
    using System;
    using XComponent.Common.ApiContext;
    using XComponent.SwaggerPetstore.Common;

	public class InitDefaultEventOnUpSwaggerPetstoreSender : AbstractSender, IInitDefaultEventOnUpSwaggerPetstoreSenderInterface
    {
		
		
		
		
		
    }
	public class AddPetAddPetOnUpSwaggerPetstoreSender : AbstractSender, IAddPetAddPetOnUpSwaggerPetstoreSenderInterface
    {
		public void CreateAddPetHttpRequest(Context context)
			{
				internalAPI.CreateAddPetHttpRequest(context);
			}
		
		
		public void CreateAddPetHttpRequest(Context context, XComponent.SwaggerPetstore.UserObject.AddPetOperation transitionEvent)
			{
				internalAPI.CreateAddPetHttpRequest(context, transitionEvent);
			}
		
		
		public void SendEvent(XComponent.SwaggerPetstore.UserObject.AddPetOperation evt)
			{
				internalAPI.SendEvent(evt);
			}
			
			public void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.AddPetOperation evt)
			{
				internalAPI.SendEvent(stdEnum, evt);
			}
		
    }
	public class GetPetByIdGetPetByIdOnUpSwaggerPetstoreSender : AbstractSender, IGetPetByIdGetPetByIdOnUpSwaggerPetstoreSenderInterface
    {
		public void CreateGetPetByIdHttpRequest(Context context)
			{
				internalAPI.CreateGetPetByIdHttpRequest(context);
			}
		
		
		public void CreateGetPetByIdHttpRequest(Context context, XComponent.SwaggerPetstore.UserObject.GetPetByIdOperation transitionEvent)
			{
				internalAPI.CreateGetPetByIdHttpRequest(context, transitionEvent);
			}
		
		
		public void SendEvent(XComponent.SwaggerPetstore.UserObject.GetPetByIdOperation evt)
			{
				internalAPI.SendEvent(evt);
			}
			
			public void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.GetPetByIdOperation evt)
			{
				internalAPI.SendEvent(stdEnum, evt);
			}
		
    }
	public class CreateAddPetHttpRequestAddPetOperationOnSendingRequestAddPetOperationSender : AbstractSender, ICreateAddPetHttpRequestAddPetOperationOnSendingRequestAddPetOperationSenderInterface
    {
		
		
		public void SendRequest_AddPetOperation(Context context, XComponent.Common.Event.DefaultEvent transitionEvent)
			{
				internalAPI.SendRequest_AddPetOperation(context, transitionEvent);
			}
		public void ReceiveSuccess_AddPetOperation(Context context, XComponent.SwaggerPetstore.UserObject.SuccessResponse transitionEvent)
			{
				internalAPI.ReceiveSuccess_AddPetOperation(context, transitionEvent);
			}
		public void ReceiveError_AddPetOperation(Context context, XComponent.SwaggerPetstore.UserObject.ErrorResponse transitionEvent)
			{
				internalAPI.ReceiveError_AddPetOperation(context, transitionEvent);
			}
		
		
		public void SendEvent(XComponent.Common.Event.DefaultEvent evt)
			{
				internalAPI.SendEvent(evt);
			}
			
			public void SendEvent(StdEnum stdEnum, XComponent.Common.Event.DefaultEvent evt)
			{
				internalAPI.SendEvent(stdEnum, evt);
			}
		public void SendEvent(XComponent.SwaggerPetstore.UserObject.SuccessResponse evt)
			{
				internalAPI.SendEvent(evt);
			}
			
			public void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.SuccessResponse evt)
			{
				internalAPI.SendEvent(stdEnum, evt);
			}
		public void SendEvent(XComponent.SwaggerPetstore.UserObject.ErrorResponse evt)
			{
				internalAPI.SendEvent(evt);
			}
			
			public void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.ErrorResponse evt)
			{
				internalAPI.SendEvent(stdEnum, evt);
			}
		
    }
	public class CreateGetPetByIdHttpRequestGetPetByIdOperationOnSendingRequestGetPetByIdOperationSender : AbstractSender, ICreateGetPetByIdHttpRequestGetPetByIdOperationOnSendingRequestGetPetByIdOperationSenderInterface
    {
		
		
		public void SendRequest_GetPetByIdOperation(Context context, XComponent.Common.Event.DefaultEvent transitionEvent)
			{
				internalAPI.SendRequest_GetPetByIdOperation(context, transitionEvent);
			}
		public void ReceiveSuccess_GetPetByIdOperation(Context context, XComponent.SwaggerPetstore.UserObject.SuccessResponse transitionEvent)
			{
				internalAPI.ReceiveSuccess_GetPetByIdOperation(context, transitionEvent);
			}
		public void ReceiveError_GetPetByIdOperation(Context context, XComponent.SwaggerPetstore.UserObject.ErrorResponse transitionEvent)
			{
				internalAPI.ReceiveError_GetPetByIdOperation(context, transitionEvent);
			}
		
		
		public void SendEvent(XComponent.Common.Event.DefaultEvent evt)
			{
				internalAPI.SendEvent(evt);
			}
			
			public void SendEvent(StdEnum stdEnum, XComponent.Common.Event.DefaultEvent evt)
			{
				internalAPI.SendEvent(stdEnum, evt);
			}
		public void SendEvent(XComponent.SwaggerPetstore.UserObject.SuccessResponse evt)
			{
				internalAPI.SendEvent(evt);
			}
			
			public void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.SuccessResponse evt)
			{
				internalAPI.SendEvent(stdEnum, evt);
			}
		public void SendEvent(XComponent.SwaggerPetstore.UserObject.ErrorResponse evt)
			{
				internalAPI.SendEvent(evt);
			}
			
			public void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.ErrorResponse evt)
			{
				internalAPI.SendEvent(stdEnum, evt);
			}
		
    }
	
}
