//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using XComponent.Common.ApiContext;
using XComponent.SwaggerPetstore.Common;

namespace XComponent.SwaggerPetstore.Common.Senders
{
    public interface IInitDefaultEventOnUpSwaggerPetstoreSenderInterface
    {


    }

    public interface IAddPetAddPetOnUpSwaggerPetstoreSenderInterface
    {
		void CreateAddPetHttpRequest(Context context, string privateTopic = null);


		void CreateAddPetHttpRequest(Context context, XComponent.SwaggerPetstore.UserObject.AddPetOperation transitionEvent, string privateTopic = null);


		void SendEvent(XComponent.SwaggerPetstore.UserObject.AddPetOperation evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.AddPetOperation evt, string privateTopic = null);

    }

    public interface IGetPetByIdGetPetByIdOnUpSwaggerPetstoreSenderInterface
    {
		void CreateGetPetByIdHttpRequest(Context context, string privateTopic = null);


		void CreateGetPetByIdHttpRequest(Context context, XComponent.SwaggerPetstore.UserObject.GetPetByIdOperation transitionEvent, string privateTopic = null);


		void SendEvent(XComponent.SwaggerPetstore.UserObject.GetPetByIdOperation evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.GetPetByIdOperation evt, string privateTopic = null);

    }

    public interface ICreateAddPetHttpRequestAddPetOperationOnSendingRequestAddPetOperationSenderInterface
    {

		void SendRequest_AddPetOperation(Context context, XComponent.Common.Event.DefaultEvent transitionEvent, string privateTopic = null);

		void ReceiveSuccess_AddPetOperation(Context context, XComponent.SwaggerPetstore.UserObject.SuccessResponse transitionEvent, string privateTopic = null);

		void ReceiveError_AddPetOperation(Context context, XComponent.SwaggerPetstore.UserObject.ErrorResponse transitionEvent, string privateTopic = null);


		void SendEvent(XComponent.Common.Event.DefaultEvent evt);

		void SendEvent(StdEnum stdEnum, XComponent.Common.Event.DefaultEvent evt);

		void SendEvent(XComponent.SwaggerPetstore.UserObject.SuccessResponse evt);

		void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.SuccessResponse evt);

		void SendEvent(XComponent.SwaggerPetstore.UserObject.ErrorResponse evt);

		void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.ErrorResponse evt);

    }

    public interface ICreateGetPetByIdHttpRequestGetPetByIdOperationOnSendingRequestGetPetByIdOperationSenderInterface
    {

		void SendRequest_GetPetByIdOperation(Context context, XComponent.Common.Event.DefaultEvent transitionEvent, string privateTopic = null);

		void ReceiveSuccess_GetPetByIdOperation(Context context, XComponent.SwaggerPetstore.UserObject.SuccessResponse transitionEvent, string privateTopic = null);

		void ReceiveError_GetPetByIdOperation(Context context, XComponent.SwaggerPetstore.UserObject.ErrorResponse transitionEvent, string privateTopic = null);


		void SendEvent(XComponent.Common.Event.DefaultEvent evt);

		void SendEvent(StdEnum stdEnum, XComponent.Common.Event.DefaultEvent evt);

		void SendEvent(XComponent.SwaggerPetstore.UserObject.SuccessResponse evt);

		void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.SuccessResponse evt);

		void SendEvent(XComponent.SwaggerPetstore.UserObject.ErrorResponse evt);

		void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.ErrorResponse evt);

    }

}