//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using XComponent.Common.ApiContext;

namespace XComponent.ChatManager.Common
{
    public interface IInternalCommunication
    {
        void Init(string configFile);

        void Send(Context context, XComponent.ChatManager.UserObject.CreateChatroom evt, string privateTopic = null);

        void Send(Context context, XComponent.ChatManager.UserObject.SentMessage evt, string privateTopic = null);

        void Send(Context context, XComponent.ChatManager.UserObject.PublishedMessage evt, string privateTopic = null);

        void Send(Context context, XComponent.ChatManager.UserObject.CloseRoom evt, string privateTopic = null);

        void SendEvent(XComponent.ChatManager.UserObject.CreateChatroom evt, string privateTopic = null);

        void SendEvent(XComponent.ChatManager.UserObject.SentMessage evt, string privateTopic = null);

        void SendEvent(XComponent.ChatManager.UserObject.PublishedMessage evt, string privateTopic = null);

        void SendEvent(XComponent.ChatManager.UserObject.CloseRoom evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.ChatManager.UserObject.CreateChatroom evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.ChatManager.UserObject.SentMessage evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.ChatManager.UserObject.PublishedMessage evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.ChatManager.UserObject.CloseRoom evt, string privateTopic = null);

    }
}
