//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.SlackProxy.Common.Senders
{
    using System;
    using XComponent.SlackProxy.Common;
    
    
    public class SenderManager
    {
		private static SendMessageSendMessageOnPublishingPublishMessageSender m_sendMessageSendMessageOnPublishingPublishMessageSender;
        
        public static SendMessageSendMessageOnPublishingPublishMessageSender SendMessageSendMessageOnPublishingPublishMessageSender
        {
            get
            {
                if ((m_sendMessageSendMessageOnPublishingPublishMessageSender == null))
                {
                    m_sendMessageSendMessageOnPublishingPublishMessageSender = new SendMessageSendMessageOnPublishingPublishMessageSender();
                }
                return m_sendMessageSendMessageOnPublishingPublishMessageSender;
            }
        }
		
    }
}
