//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.SwaggerPetstore.Common.Senders
{
    using System;
    using XComponent.SwaggerPetstore.Common;
    
    
    public class SenderManager
    {
		private static InitDefaultEventOnUpSwaggerPetstoreSender m_initDefaultEventOnUpSwaggerPetstoreSender;
        
        public static InitDefaultEventOnUpSwaggerPetstoreSender InitDefaultEventOnUpSwaggerPetstoreSender
        {
            get
            {
                if ((m_initDefaultEventOnUpSwaggerPetstoreSender == null))
                {
                    m_initDefaultEventOnUpSwaggerPetstoreSender = new InitDefaultEventOnUpSwaggerPetstoreSender();
                }
                return m_initDefaultEventOnUpSwaggerPetstoreSender;
            }
        }
		private static AddPetAddPetOnUpSwaggerPetstoreSender m_addPetAddPetOnUpSwaggerPetstoreSender;
        
        public static AddPetAddPetOnUpSwaggerPetstoreSender AddPetAddPetOnUpSwaggerPetstoreSender
        {
            get
            {
                if ((m_addPetAddPetOnUpSwaggerPetstoreSender == null))
                {
                    m_addPetAddPetOnUpSwaggerPetstoreSender = new AddPetAddPetOnUpSwaggerPetstoreSender();
                }
                return m_addPetAddPetOnUpSwaggerPetstoreSender;
            }
        }
		private static GetPetByIdGetPetByIdOnUpSwaggerPetstoreSender m_getPetByIdGetPetByIdOnUpSwaggerPetstoreSender;
        
        public static GetPetByIdGetPetByIdOnUpSwaggerPetstoreSender GetPetByIdGetPetByIdOnUpSwaggerPetstoreSender
        {
            get
            {
                if ((m_getPetByIdGetPetByIdOnUpSwaggerPetstoreSender == null))
                {
                    m_getPetByIdGetPetByIdOnUpSwaggerPetstoreSender = new GetPetByIdGetPetByIdOnUpSwaggerPetstoreSender();
                }
                return m_getPetByIdGetPetByIdOnUpSwaggerPetstoreSender;
            }
        }
		private static CreateAddPetHttpRequestAddPetOperationOnSendingRequestAddPetOperationSender m_createAddPetHttpRequestAddPetOperationOnSendingRequestAddPetOperationSender;
        
        public static CreateAddPetHttpRequestAddPetOperationOnSendingRequestAddPetOperationSender CreateAddPetHttpRequestAddPetOperationOnSendingRequestAddPetOperationSender
        {
            get
            {
                if ((m_createAddPetHttpRequestAddPetOperationOnSendingRequestAddPetOperationSender == null))
                {
                    m_createAddPetHttpRequestAddPetOperationOnSendingRequestAddPetOperationSender = new CreateAddPetHttpRequestAddPetOperationOnSendingRequestAddPetOperationSender();
                }
                return m_createAddPetHttpRequestAddPetOperationOnSendingRequestAddPetOperationSender;
            }
        }
		private static CreateGetPetByIdHttpRequestGetPetByIdOperationOnSendingRequestGetPetByIdOperationSender m_createGetPetByIdHttpRequestGetPetByIdOperationOnSendingRequestGetPetByIdOperationSender;
        
        public static CreateGetPetByIdHttpRequestGetPetByIdOperationOnSendingRequestGetPetByIdOperationSender CreateGetPetByIdHttpRequestGetPetByIdOperationOnSendingRequestGetPetByIdOperationSender
        {
            get
            {
                if ((m_createGetPetByIdHttpRequestGetPetByIdOperationOnSendingRequestGetPetByIdOperationSender == null))
                {
                    m_createGetPetByIdHttpRequestGetPetByIdOperationOnSendingRequestGetPetByIdOperationSender = new CreateGetPetByIdHttpRequestGetPetByIdOperationOnSendingRequestGetPetByIdOperationSender();
                }
                return m_createGetPetByIdHttpRequestGetPetByIdOperationOnSendingRequestGetPetByIdOperationSender;
            }
        }
		
    }
}
