//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.HelloWorld.Common.Senders
{
    using System;
    using XComponent.HelloWorld.Common;
    
    
    public class SenderManager
    {
		private static SayHelloSayHelloOnDoneHelloResponseSender m_sayHelloSayHelloOnDoneHelloResponseSender;
        
        public static SayHelloSayHelloOnDoneHelloResponseSender SayHelloSayHelloOnDoneHelloResponseSender
        {
            get
            {
                if ((m_sayHelloSayHelloOnDoneHelloResponseSender == null))
                {
                    m_sayHelloSayHelloOnDoneHelloResponseSender = new SayHelloSayHelloOnDoneHelloResponseSender();
                }
                return m_sayHelloSayHelloOnDoneHelloResponseSender;
            }
        }
		
    }
}
