using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("XComponent.ChatManager.TriggeredMethod")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("neomantis")]
[assembly: AssemblyProduct("XComponent")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
