//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.TradeCapture.Common
{
    using System;
    
    public enum TransactionStateEnum
    {
		Validation = 4,
			
		ValidationError = 5,
			
		TransactionRejected = 3,
			
		Mapping = 1,
			
		ErrorOnMapping = 0,
			
		TransactionAccepted = 2,
			
		
    }
}