//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XComponent.Referential.Common.Senders
{
    using System;
    using XComponent.Common.ApiContext;
    using XComponent.Referential.Common;
    
	public interface IAddInstrumentInstrumentOnReferentialReferentialSenderInterface
    {
		
		
		
		
		
    }
	
}
