//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace XComponent.SwaggerPetstore.Common
{
    public enum CreateUserOperationStateEnum
    {
		ErrorResponseReceived = 0,
		RequestSent = 1,
		SendingRequest = 2,
		SuccessResponseReceived = 3,
    }
}