//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using XComponent.Common.ApiContext;

namespace XComponent.SwaggerPetstore.Common
{
    public interface IInternalCommunication
    {
        void Init(string configFile);

        void Send(Context context, XComponent.Common.Event.DefaultEvent evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.AddPet evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.AddPetOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.UpdatePet evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.UpdatePetOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.FindPetsByStatus evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.FindPetsByStatusOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.FindPetsByTags evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.FindPetsByTagsOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.GetPetById evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.GetPetByIdOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.UpdatePetWithForm evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.UpdatePetWithFormOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.DeletePet evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.DeletePetOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.UploadFile evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.UploadFileOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.GetInventory evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.GetInventoryOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.PlaceOrder evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.PlaceOrderOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.GetOrderById evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.GetOrderByIdOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.DeleteOrder evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.DeleteOrderOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.CreateUser evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.CreateUserOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.CreateUsersWithArrayInput evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.CreateUsersWithArrayInputOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.CreateUsersWithListInput evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.CreateUsersWithListInputOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.LoginUser evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.LoginUserOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.LogoutUser evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.LogoutUserOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.GetUserByName evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.GetUserByNameOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.UpdateUser evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.UpdateUserOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.DeleteUser evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.DeleteUserOperation evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.SuccessResponse evt, string privateTopic = null);

        void Send(Context context, XComponent.SwaggerPetstore.UserObject.ErrorResponse evt, string privateTopic = null);

        void SendEvent(XComponent.Common.Event.DefaultEvent evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.AddPet evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.AddPetOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.UpdatePet evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.UpdatePetOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.FindPetsByStatus evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.FindPetsByStatusOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.FindPetsByTags evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.FindPetsByTagsOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.GetPetById evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.GetPetByIdOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.UpdatePetWithForm evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.UpdatePetWithFormOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.DeletePet evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.DeletePetOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.UploadFile evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.UploadFileOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.GetInventory evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.GetInventoryOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.PlaceOrder evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.PlaceOrderOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.GetOrderById evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.GetOrderByIdOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.DeleteOrder evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.DeleteOrderOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.CreateUser evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.CreateUserOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.CreateUsersWithArrayInput evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.CreateUsersWithArrayInputOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.CreateUsersWithListInput evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.CreateUsersWithListInputOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.LoginUser evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.LoginUserOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.LogoutUser evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.LogoutUserOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.GetUserByName evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.GetUserByNameOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.UpdateUser evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.UpdateUserOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.DeleteUser evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.DeleteUserOperation evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.SuccessResponse evt, string privateTopic = null);

        void SendEvent(XComponent.SwaggerPetstore.UserObject.ErrorResponse evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.Common.Event.DefaultEvent evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.AddPet evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.AddPetOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.UpdatePet evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.UpdatePetOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.FindPetsByStatus evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.FindPetsByStatusOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.FindPetsByTags evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.FindPetsByTagsOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.GetPetById evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.GetPetByIdOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.UpdatePetWithForm evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.UpdatePetWithFormOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.DeletePet evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.DeletePetOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.UploadFile evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.UploadFileOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.GetInventory evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.GetInventoryOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.PlaceOrder evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.PlaceOrderOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.GetOrderById evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.GetOrderByIdOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.DeleteOrder evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.DeleteOrderOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.CreateUser evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.CreateUserOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.CreateUsersWithArrayInput evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.CreateUsersWithArrayInputOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.CreateUsersWithListInput evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.CreateUsersWithListInputOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.LoginUser evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.LoginUserOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.LogoutUser evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.LogoutUserOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.GetUserByName evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.GetUserByNameOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.UpdateUser evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.UpdateUserOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.DeleteUser evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.DeleteUserOperation evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.SuccessResponse evt, string privateTopic = null);

        void SendEvent(StdEnum stdEnum, XComponent.SwaggerPetstore.UserObject.ErrorResponse evt, string privateTopic = null);

    }
}
