//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace XComponent.SwaggerPetstore.Common
{
    public enum StdEnum
    {
		AddPetOperation = -1573098133,
		CreateUserOperation = -1885035300,
		CreateUsersWithArrayInputOperation = 1610894133,
		CreateUsersWithListInputOperation = -778049146,
		DeleteOrderOperation = -1736304006,
		DeletePetOperation = -2038525811,
		DeleteUserOperation = -647013823,
		FindPetsByStatusOperation = 441322543,
		FindPetsByTagsOperation = 715370505,
		GetInventoryOperation = -27939533,
		GetOrderByIdOperation = -1136586326,
		GetPetByIdOperation = 1341262500,
		GetUserByNameOperation = -1901015653,
		LoginUserOperation = 2145862436,
		LogoutUserOperation = 1845274015,
		PlaceOrderOperation = 1641275182,
		SwaggerPetstore = -1217457941,
		UpdatePetOperation = -1548009360,
		UpdatePetWithFormOperation = -304199001,
		UpdateUserOperation = -752139183,
		UploadFileOperation = 681824184,
    }
}