//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace XComponent.Authentication.Common
{
    public enum AuthenticationStateEnum
    {
		EntryPoint = 0,
		InitializationError = 1,
		Initializing = 2,
		Up = 3,
    }
}