//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XComponent.Authentication.Common
{
    using System;
    
    public enum AuthenticationStateEnum
    {
		EntryPoint = 0,
			
		Initializing = 2,
			
		Up = 3,
			
		InitializationError = 1,
			
		
    }
}