//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace XComponent.Authentication.Common
{
    public enum HeartBeatStateEnum
    {
		Up = 0,
    }
}