//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using XComponent.Engine.Processing;
using XComponent.Common.Processing;
using XComponent.Engine.Processing.Domain;
using XComponent.Common.ApiContext;
using XComponent.Communication;

namespace XComponent.Authentication.Common
{
    public class InternalCommunication : IInternalCommunication
    {
        private const string ComponentName = "Authentication";

		private IAgentManager _agentManager;
        private Dictionary<int, EngineAgent> _engineAgentsById = new Dictionary<int, EngineAgent>();
        private Dictionary<int, List<EngineAgent>> _engineAgentsByStateMachine = new Dictionary<int, List<EngineAgent>>();

        public InternalCommunication(IAgentManager agentManager)
        {
            _agentManager = agentManager;
        }
		
        public void Init(string configFile)
        {
			foreach( var engineAgent in _agentManager.FilterEngineAgentForInternalAPI(769565298))
			{
				_engineAgentsById.Add(engineAgent.Id, engineAgent);
				
				foreach( var detail in Agent.getAgentDetails(engineAgent))
				{
					if (detail.Key.Equals(769565298))
					{
						foreach( var stateMachineCode in detail.Value )
						{
							if(!_engineAgentsByStateMachine.ContainsKey(stateMachineCode))
							{
								_engineAgentsByStateMachine.Add(stateMachineCode, new List<EngineAgent>());
							}

							_engineAgentsByStateMachine[stateMachineCode].Add(engineAgent);
						}
					}
				}
			}
        }

		public void Send(Context context, XComponent.Common.Event.DefaultEvent evt, string privateTopic = null)
        {
            var incomingEvent = new IncomingEvent(evt != null ? evt : new XComponent.Common.Event.DefaultEvent(), IncomingEventType.Transition, HeaderFactory.Create(context, 18, privateTopic));
            Agent.Post(_engineAgentsById[context.AgentId], incomingEvent);
        }
        
		public void SendEvent(XComponent.Common.Event.DefaultEvent evt, string privateTopic = null)
        {
            SendEvent(StdEnum.Authentication, evt != null ? evt : new XComponent.Common.Event.DefaultEvent(), privateTopic);
            SendEvent(StdEnum.HeartBeat, evt != null ? evt : new XComponent.Common.Event.DefaultEvent(), privateTopic);
		}

		public void SendEvent(StdEnum stateMachineEnum, XComponent.Common.Event.DefaultEvent evt, string privateTopic = null)
        {
            var incomingEvent = new IncomingEvent(evt != null ? evt : new XComponent.Common.Event.DefaultEvent(), IncomingEventType.Transition, HeaderFactory.Create(18, (int)stateMachineEnum, 769565298, privateTopic));
			PostOnStateMachine(incomingEvent, stateMachineEnum);
        }

		public void Send(Context context, XComponent.Authentication.UserObject.InitializationSuccess evt, string privateTopic = null)
        {
            var incomingEvent = new IncomingEvent(evt != null ? evt : new XComponent.Authentication.UserObject.InitializationSuccess(), IncomingEventType.Transition, HeaderFactory.Create(context, 7, privateTopic));
            Agent.Post(_engineAgentsById[context.AgentId], incomingEvent);
        }
        
		public void SendEvent(XComponent.Authentication.UserObject.InitializationSuccess evt, string privateTopic = null)
        {
            SendEvent(StdEnum.Authentication, evt != null ? evt : new XComponent.Authentication.UserObject.InitializationSuccess(), privateTopic);
		}

		public void SendEvent(StdEnum stateMachineEnum, XComponent.Authentication.UserObject.InitializationSuccess evt, string privateTopic = null)
        {
            var incomingEvent = new IncomingEvent(evt != null ? evt : new XComponent.Authentication.UserObject.InitializationSuccess(), IncomingEventType.Transition, HeaderFactory.Create(7, (int)stateMachineEnum, 769565298, privateTopic));
			PostOnStateMachine(incomingEvent, stateMachineEnum);
        }

		public void Send(Context context, XComponent.Authentication.UserObject.InitializationError evt, string privateTopic = null)
        {
            var incomingEvent = new IncomingEvent(evt != null ? evt : new XComponent.Authentication.UserObject.InitializationError(), IncomingEventType.Transition, HeaderFactory.Create(context, 6, privateTopic));
            Agent.Post(_engineAgentsById[context.AgentId], incomingEvent);
        }
        
		public void SendEvent(XComponent.Authentication.UserObject.InitializationError evt, string privateTopic = null)
        {
            SendEvent(StdEnum.Authentication, evt != null ? evt : new XComponent.Authentication.UserObject.InitializationError(), privateTopic);
		}

		public void SendEvent(StdEnum stateMachineEnum, XComponent.Authentication.UserObject.InitializationError evt, string privateTopic = null)
        {
            var incomingEvent = new IncomingEvent(evt != null ? evt : new XComponent.Authentication.UserObject.InitializationError(), IncomingEventType.Transition, HeaderFactory.Create(6, (int)stateMachineEnum, 769565298, privateTopic));
			PostOnStateMachine(incomingEvent, stateMachineEnum);
        }

		public void Send(Context context, XComponent.Authentication.UserObject.CheckLogin evt, string privateTopic = null)
        {
            var incomingEvent = new IncomingEvent(evt != null ? evt : new XComponent.Authentication.UserObject.CheckLogin(), IncomingEventType.Transition, HeaderFactory.Create(context, 4, privateTopic));
            Agent.Post(_engineAgentsById[context.AgentId], incomingEvent);
        }
        
		public void SendEvent(XComponent.Authentication.UserObject.CheckLogin evt, string privateTopic = null)
        {
            SendEvent(StdEnum.Authentication, evt != null ? evt : new XComponent.Authentication.UserObject.CheckLogin(), privateTopic);
		}

		public void SendEvent(StdEnum stateMachineEnum, XComponent.Authentication.UserObject.CheckLogin evt, string privateTopic = null)
        {
            var incomingEvent = new IncomingEvent(evt != null ? evt : new XComponent.Authentication.UserObject.CheckLogin(), IncomingEventType.Transition, HeaderFactory.Create(4, (int)stateMachineEnum, 769565298, privateTopic));
			PostOnStateMachine(incomingEvent, stateMachineEnum);
        }

		public void Send(Context context, XComponent.Authentication.UserObject.CreateHeartBeat evt, string privateTopic = null)
        {
            var incomingEvent = new IncomingEvent(evt != null ? evt : new XComponent.Authentication.UserObject.CreateHeartBeat(), IncomingEventType.Transition, HeaderFactory.Create(context, 5, privateTopic));
            Agent.Post(_engineAgentsById[context.AgentId], incomingEvent);
        }
        
		public void SendEvent(XComponent.Authentication.UserObject.CreateHeartBeat evt, string privateTopic = null)
        {
            SendEvent(StdEnum.Authentication, evt != null ? evt : new XComponent.Authentication.UserObject.CreateHeartBeat(), privateTopic);
		}

		public void SendEvent(StdEnum stateMachineEnum, XComponent.Authentication.UserObject.CreateHeartBeat evt, string privateTopic = null)
        {
            var incomingEvent = new IncomingEvent(evt != null ? evt : new XComponent.Authentication.UserObject.CreateHeartBeat(), IncomingEventType.Transition, HeaderFactory.Create(5, (int)stateMachineEnum, 769565298, privateTopic));
			PostOnStateMachine(incomingEvent, stateMachineEnum);
        }

		public void Send(Context context, XComponent.Authentication.UserObject.LoginSuccess evt, string privateTopic = null)
        {
            var incomingEvent = new IncomingEvent(evt != null ? evt : new XComponent.Authentication.UserObject.LoginSuccess(), IncomingEventType.Transition, HeaderFactory.Create(context, 9, privateTopic));
            Agent.Post(_engineAgentsById[context.AgentId], incomingEvent);
        }
        
		public void SendEvent(XComponent.Authentication.UserObject.LoginSuccess evt, string privateTopic = null)
        {
            SendEvent(StdEnum.LoginStatus, evt != null ? evt : new XComponent.Authentication.UserObject.LoginSuccess(), privateTopic);
		}

		public void SendEvent(StdEnum stateMachineEnum, XComponent.Authentication.UserObject.LoginSuccess evt, string privateTopic = null)
        {
            var incomingEvent = new IncomingEvent(evt != null ? evt : new XComponent.Authentication.UserObject.LoginSuccess(), IncomingEventType.Transition, HeaderFactory.Create(9, (int)stateMachineEnum, 769565298, privateTopic));
			PostOnStateMachine(incomingEvent, stateMachineEnum);
        }

		public void Send(Context context, XComponent.Authentication.UserObject.LoginError evt, string privateTopic = null)
        {
            var incomingEvent = new IncomingEvent(evt != null ? evt : new XComponent.Authentication.UserObject.LoginError(), IncomingEventType.Transition, HeaderFactory.Create(context, 8, privateTopic));
            Agent.Post(_engineAgentsById[context.AgentId], incomingEvent);
        }
        
		public void SendEvent(XComponent.Authentication.UserObject.LoginError evt, string privateTopic = null)
        {
            SendEvent(StdEnum.LoginStatus, evt != null ? evt : new XComponent.Authentication.UserObject.LoginError(), privateTopic);
		}

		public void SendEvent(StdEnum stateMachineEnum, XComponent.Authentication.UserObject.LoginError evt, string privateTopic = null)
        {
            var incomingEvent = new IncomingEvent(evt != null ? evt : new XComponent.Authentication.UserObject.LoginError(), IncomingEventType.Transition, HeaderFactory.Create(8, (int)stateMachineEnum, 769565298, privateTopic));
			PostOnStateMachine(incomingEvent, stateMachineEnum);
        }

		private void PostOnStateMachine(IncomingEvent incomingEvent, StdEnum stateMachineEnum)
		{
			foreach(var engineAgent in GetEngineAgents(stateMachineEnum))
			{
				Agent.Post(engineAgent, incomingEvent);
			}
		}

		private IEnumerable<EngineAgent> GetEngineAgents(StdEnum stateMachineEnum)
        {
			switch(stateMachineEnum)
			{
				case StdEnum.Authentication :
					return _engineAgentsByStateMachine[769565298];
				case StdEnum.LoginStatus :
					return _engineAgentsByStateMachine[1247698004];
				case StdEnum.HeartBeat :
					return _engineAgentsByStateMachine[-1613370233];
			}

            return new List<EngineAgent>();
        }
    }
}
