//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using XComponent.Order.Common;

namespace XComponent.Order.Common.Senders
{
    public class AbstractSender
    {
        internal static IInternalAPI _internalAPI;
        
        public static void Init(IInternalAPI internalAPI)
        {            
            _internalAPI = internalAPI;
        }
    }
}