//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using XComponent.Order.Common;

namespace XComponent.Order.Common.Senders
{
    public class SenderManager
    {
		private static ExecuteExecutionInputOnExecutedOrderSender _executeExecutionInputOnExecutedOrderSender;
		private static PartiallyExecuteExecutionInputOnPartiallyExecutedOrderSender _partiallyExecuteExecutionInputOnPartiallyExecutedOrderSender;
		private static CreateOrderOrderInputOnPendingOrderSender _createOrderOrderInputOnPendingOrderSender;
		private static PublishOrderCreationOrderCreationOnCreatedCreationFacadeSender _publishOrderCreationOrderCreationOnCreatedCreationFacadeSender;
		private static PublishOrderFilledOrderExecutionOnFilledExecutionFacadeSender _publishOrderFilledOrderExecutionOnFilledExecutionFacadeSender;
		private static PublishOrderPartiallyFilledOrderExecutionOnPartiallyFilledPartialExecutionFacadeSender _publishOrderPartiallyFilledOrderExecutionOnPartiallyFilledPartialExecutionFacadeSender;

        public static ExecuteExecutionInputOnExecutedOrderSender ExecuteExecutionInputOnExecutedOrderSender
        {
            get
            {
                return _executeExecutionInputOnExecutedOrderSender ??
                       (_executeExecutionInputOnExecutedOrderSender = new ExecuteExecutionInputOnExecutedOrderSender());
            }
        }

        public static PartiallyExecuteExecutionInputOnPartiallyExecutedOrderSender PartiallyExecuteExecutionInputOnPartiallyExecutedOrderSender
        {
            get
            {
                return _partiallyExecuteExecutionInputOnPartiallyExecutedOrderSender ??
                       (_partiallyExecuteExecutionInputOnPartiallyExecutedOrderSender = new PartiallyExecuteExecutionInputOnPartiallyExecutedOrderSender());
            }
        }

        public static CreateOrderOrderInputOnPendingOrderSender CreateOrderOrderInputOnPendingOrderSender
        {
            get
            {
                return _createOrderOrderInputOnPendingOrderSender ??
                       (_createOrderOrderInputOnPendingOrderSender = new CreateOrderOrderInputOnPendingOrderSender());
            }
        }

        public static PublishOrderCreationOrderCreationOnCreatedCreationFacadeSender PublishOrderCreationOrderCreationOnCreatedCreationFacadeSender
        {
            get
            {
                return _publishOrderCreationOrderCreationOnCreatedCreationFacadeSender ??
                       (_publishOrderCreationOrderCreationOnCreatedCreationFacadeSender = new PublishOrderCreationOrderCreationOnCreatedCreationFacadeSender());
            }
        }

        public static PublishOrderFilledOrderExecutionOnFilledExecutionFacadeSender PublishOrderFilledOrderExecutionOnFilledExecutionFacadeSender
        {
            get
            {
                return _publishOrderFilledOrderExecutionOnFilledExecutionFacadeSender ??
                       (_publishOrderFilledOrderExecutionOnFilledExecutionFacadeSender = new PublishOrderFilledOrderExecutionOnFilledExecutionFacadeSender());
            }
        }

        public static PublishOrderPartiallyFilledOrderExecutionOnPartiallyFilledPartialExecutionFacadeSender PublishOrderPartiallyFilledOrderExecutionOnPartiallyFilledPartialExecutionFacadeSender
        {
            get
            {
                return _publishOrderPartiallyFilledOrderExecutionOnPartiallyFilledPartialExecutionFacadeSender ??
                       (_publishOrderPartiallyFilledOrderExecutionOnPartiallyFilledPartialExecutionFacadeSender = new PublishOrderPartiallyFilledOrderExecutionOnPartiallyFilledPartialExecutionFacadeSender());
            }
        }

    }
}
