//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using XComponent.Common.ApiContext;
using XComponent.Order.Common;

namespace XComponent.Order.Common.Senders
{
    public class ExecuteExecutionInputOnExecutedOrderSender : AbstractSender, IExecuteExecutionInputOnExecutedOrderSenderInterface
    {
		public void PublishOrderFilled(Context context, string privateTopic = null)
		{
			_internalAPI.PublishOrderFilled(context, privateTopic);
		}


		public void PublishOrderFilled(Context context, XComponent.Order.UserObject.OrderExecution transitionEvent, string privateTopic = null)
		{
			_internalAPI.PublishOrderFilled(context, transitionEvent, privateTopic);
		}


		public void SendEvent(XComponent.Order.UserObject.OrderExecution evt, string privateTopic = null)
		{
			_internalAPI.SendEvent(evt, privateTopic);
		}

		public void SendEvent(StdEnum stdEnum, XComponent.Order.UserObject.OrderExecution evt, string privateTopic = null)
		{
			_internalAPI.SendEvent(stdEnum, evt, privateTopic);
		}

    }

    public class PartiallyExecuteExecutionInputOnPartiallyExecutedOrderSender : AbstractSender, IPartiallyExecuteExecutionInputOnPartiallyExecutedOrderSenderInterface
    {
		public void PublishOrderPartiallyFilled(Context context, string privateTopic = null)
		{
			_internalAPI.PublishOrderPartiallyFilled(context, privateTopic);
		}


		public void PublishOrderPartiallyFilled(Context context, XComponent.Order.UserObject.OrderExecution transitionEvent, string privateTopic = null)
		{
			_internalAPI.PublishOrderPartiallyFilled(context, transitionEvent, privateTopic);
		}


		public void SendEvent(XComponent.Order.UserObject.OrderExecution evt, string privateTopic = null)
		{
			_internalAPI.SendEvent(evt, privateTopic);
		}

		public void SendEvent(StdEnum stdEnum, XComponent.Order.UserObject.OrderExecution evt, string privateTopic = null)
		{
			_internalAPI.SendEvent(stdEnum, evt, privateTopic);
		}

    }

    public class CreateOrderOrderInputOnPendingOrderSender : AbstractSender, ICreateOrderOrderInputOnPendingOrderSenderInterface
    {
		public void PublishOrderCreation(Context context, string privateTopic = null)
		{
			_internalAPI.PublishOrderCreation(context, privateTopic);
		}


		public void PublishOrderCreation(Context context, XComponent.Order.UserObject.OrderCreation transitionEvent, string privateTopic = null)
		{
			_internalAPI.PublishOrderCreation(context, transitionEvent, privateTopic);
		}


		public void SendEvent(XComponent.Order.UserObject.OrderCreation evt, string privateTopic = null)
		{
			_internalAPI.SendEvent(evt, privateTopic);
		}

		public void SendEvent(StdEnum stdEnum, XComponent.Order.UserObject.OrderCreation evt, string privateTopic = null)
		{
			_internalAPI.SendEvent(stdEnum, evt, privateTopic);
		}

    }

    public class PublishOrderCreationOrderCreationOnCreatedCreationFacadeSender : AbstractSender, IPublishOrderCreationOrderCreationOnCreatedCreationFacadeSenderInterface
    {


    }

    public class PublishOrderFilledOrderExecutionOnFilledExecutionFacadeSender : AbstractSender, IPublishOrderFilledOrderExecutionOnFilledExecutionFacadeSenderInterface
    {


    }

    public class PublishOrderPartiallyFilledOrderExecutionOnPartiallyFilledPartialExecutionFacadeSender : AbstractSender, IPublishOrderPartiallyFilledOrderExecutionOnPartiallyFilledPartialExecutionFacadeSenderInterface
    {


    }

}